apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-task
spec:
  workspaces:
    - name: source
  steps:
    # Step 1: Clone repo
    - name: clone-repo
      image: alpine/git
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        git clone https://github.com/afsanafaizi/education-trading-backend.git .
        ls -la

    # Step 2: Build with Maven
    - name: build
      image: maven:3.9.6-eclipse-temurin-17
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        mvn clean package
